//! Protocol Buffer Generated Types
//! Generated from .proto files in /proto directory

// Placeholder for generated protobuf modules
// These would be generated by prost-build during compilation

pub mod types {
    use serde::{Deserialize, Serialize};

    #[derive(Debug, Clone, Serialize, Deserialize)]
    pub struct OrderRequest {
        pub client_order_id: String,
        pub symbol: String,
        pub side: i32,
        pub order_type: i32,
        pub quantity: String,
        pub price: Option<String>,
    }

    #[derive(Debug, Clone, Serialize, Deserialize)]
    pub struct ExecutionReport {
        pub order_id: String,
        pub client_order_id: String,
        pub status: i32,
        pub filled_quantity: String,
        pub avg_price: Option<String>,
    }

    #[derive(Debug, Clone, Serialize, Deserialize)]
    pub struct PositionUpdate {
        pub account_id: String,
        pub symbol: String,
        pub quantity: String,
        pub avg_price: String,
        pub unrealized_pnl: String,
        pub realized_pnl: String,
    }
}